POST https://wppuuivsgzvzsfpvrrxu.supabase.co/auth/v1/token?grant_type=password
Accept: application/json
Content-Type: application/json
apiKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwcHV1aXZzZ3p2enNmcHZycnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NDYyMjMsImV4cCI6MjA1MDAyMjIyM30.YN408Rv9xCcjiM9nH2wG0t5NYTmfeNYw6HruhtlVvTk

{
  "email": "",
  "password": ""
}